/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import Vista.FacturaGUI;
import Vista.PersonaTercerosView;
import Vista.RepLegalView;

/**
 *
 * @author Fucker
 */
public class GestionInventarioHogarPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form GestionInventarioHogarPrincipal
     */
    public GestionInventarioHogarPrincipal() {
        
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnMinimized1 = new javax.swing.JLabel();
        btnMaximize1 = new javax.swing.JLabel();
        btnClose1 = new javax.swing.JLabel();
        btnRestore1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        btnSalir = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        btnRegProductos = new javax.swing.JMenuItem();
        btnCatProd = new javax.swing.JMenuItem();
        btnAdminInventario = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        btnGestionTerceros = new javax.swing.JMenuItem();
        btnRepresLegal = new javax.swing.JMenuItem();
        btnActEco = new javax.swing.JMenuItem();
        btnSucTerce = new javax.swing.JMenuItem();
        btnEmpleados = new javax.swing.JMenuItem();
        btnFacturacion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestión Inventario - Hogar de La Joven - Club Rotario Ibagué");
        setBackground(new java.awt.Color(51, 51, 51));
        setFocusCycleRoot(false);
        setUndecorated(true);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/rsz_hogar.png"))); // NOI18N
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/rsz_hogarblanco.png"))); // NOI18N
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setOpaque(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1213, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));

        btnMinimized1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8_Minimize_Window_38px_1.png"))); // NOI18N
        btnMinimized1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMinimized1MouseClicked(evt);
            }
        });

        btnMaximize1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8_Maximize_Window_48px_1.png"))); // NOI18N
        btnMaximize1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMaximize1MouseClicked(evt);
            }
        });

        btnClose1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8_Cancel_48px.png"))); // NOI18N
        btnClose1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnClose1MouseClicked(evt);
            }
        });

        btnRestore1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8_Maximize_Window_38px.png"))); // NOI18N
        btnRestore1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRestore1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnMinimized1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnRestore1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMaximize1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClose1)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnMinimized1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRestore1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMaximize1)
                    .addComponent(btnClose1))
                .addGap(0, 10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 556, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenuBar1.setBackground(new java.awt.Color(4, 0, 16));
        jMenuBar1.setBorder(null);
        jMenuBar1.setForeground(new java.awt.Color(204, 204, 204));
        jMenuBar1.setBorderPainted(false);
        jMenuBar1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N

        jMenu1.setBorder(null);
        jMenu1.setForeground(new java.awt.Color(204, 204, 204));
        jMenu1.setText("Archivo");
        jMenu1.setBorderPainted(false);
        jMenu1.setContentAreaFilled(false);
        jMenu1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jMenu1.setMargin(new java.awt.Insets(10, 10, 10, 10));
        jMenu1.setOpaque(false);

        btnSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        btnSalir.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        btnSalir.setForeground(new java.awt.Color(51, 51, 51));
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        jMenu1.add(btnSalir);

        jMenuBar1.add(jMenu1);

        jMenu2.setForeground(new java.awt.Color(204, 204, 204));
        jMenu2.setText("Administración");
        jMenu2.setBorderPainted(false);
        jMenu2.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jMenu2.setOpaque(false);

        jMenu3.setForeground(new java.awt.Color(51, 51, 51));
        jMenu3.setText("Inventario");
        jMenu3.setBorderPainted(false);
        jMenu3.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jMenu3.setOpaque(false);

        btnRegProductos.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        btnRegProductos.setForeground(new java.awt.Color(51, 51, 51));
        btnRegProductos.setText("Registro de Productos");
        btnRegProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegProductosActionPerformed(evt);
            }
        });
        jMenu3.add(btnRegProductos);

        btnCatProd.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        btnCatProd.setForeground(new java.awt.Color(51, 51, 51));
        btnCatProd.setText("Categoría de Productos");
        btnCatProd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCatProdActionPerformed(evt);
            }
        });
        jMenu3.add(btnCatProd);

        btnAdminInventario.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        btnAdminInventario.setForeground(new java.awt.Color(51, 51, 51));
        btnAdminInventario.setText("Administración de Inventarios");
        btnAdminInventario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdminInventarioActionPerformed(evt);
            }
        });
        jMenu3.add(btnAdminInventario);

        jMenu2.add(jMenu3);

        jMenu4.setForeground(new java.awt.Color(51, 51, 51));
        jMenu4.setText("Administración de Terceros");
        jMenu4.setBorderPainted(false);
        jMenu4.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jMenu4.setOpaque(false);

        btnGestionTerceros.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        btnGestionTerceros.setForeground(new java.awt.Color(51, 51, 51));
        btnGestionTerceros.setText("Gestión de Terceros");
        btnGestionTerceros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGestionTercerosActionPerformed(evt);
            }
        });
        jMenu4.add(btnGestionTerceros);

        btnRepresLegal.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        btnRepresLegal.setForeground(new java.awt.Color(51, 51, 51));
        btnRepresLegal.setText("Registro de Representante Legal");
        btnRepresLegal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRepresLegalActionPerformed(evt);
            }
        });
        jMenu4.add(btnRepresLegal);

        btnActEco.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        btnActEco.setForeground(new java.awt.Color(51, 51, 51));
        btnActEco.setText("Gestión Actividad Económica Tercero");
        btnActEco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActEcoActionPerformed(evt);
            }
        });
        jMenu4.add(btnActEco);

        btnSucTerce.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        btnSucTerce.setForeground(new java.awt.Color(51, 51, 51));
        btnSucTerce.setText("Registro Sucursales de Terceros");
        btnSucTerce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSucTerceActionPerformed(evt);
            }
        });
        jMenu4.add(btnSucTerce);

        jMenu2.add(jMenu4);

        btnEmpleados.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        btnEmpleados.setForeground(new java.awt.Color(51, 51, 51));
        btnEmpleados.setText("Administración Empleados");
        btnEmpleados.setBorderPainted(false);
        btnEmpleados.setOpaque(false);
        btnEmpleados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmpleadosActionPerformed(evt);
            }
        });
        jMenu2.add(btnEmpleados);

        btnFacturacion.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        btnFacturacion.setForeground(new java.awt.Color(51, 51, 51));
        btnFacturacion.setText("Facturación");
        btnFacturacion.setBorderPainted(false);
        btnFacturacion.setOpaque(false);
        btnFacturacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFacturacionActionPerformed(evt);
            }
        });
        jMenu2.add(btnFacturacion);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(540, 540, 540)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(190, 190, 190)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 636, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRepresLegalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRepresLegalActionPerformed
        RepLegalView rplv = null;
        rplv=rplv.inicializarRepLegal();
        rplv.setVisible(true);
    }//GEN-LAST:event_btnRepresLegalActionPerformed

    private void btnSucTerceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSucTerceActionPerformed
        SucursalView sv = null;
        sv=sv.inicializarSucursal();
        sv.setVisible(true);
    }//GEN-LAST:event_btnSucTerceActionPerformed

    private void btnFacturacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFacturacionActionPerformed
        FacturaGUI fg = new FacturaGUI();
        fg.setVisible(true);
    }//GEN-LAST:event_btnFacturacionActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnRegProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegProductosActionPerformed
        ProductoView pv = null;
        pv=pv.inicializarProducto();
        pv.setVisible(true);
    }//GEN-LAST:event_btnRegProductosActionPerformed

    private void btnCatProdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCatProdActionPerformed
         CategoriaView cv=null;
         cv=cv.inicializarCategoriaView();
         cv.setVisible(true);
    }//GEN-LAST:event_btnCatProdActionPerformed

    private void btnAdminInventarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdminInventarioActionPerformed
        InventarioView iv = null ;
        iv=iv.inicializarInventario();
        iv.setVisible(true);
    }//GEN-LAST:event_btnAdminInventarioActionPerformed

    private void btnActEcoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActEcoActionPerformed
        ActividadesView ace = null;
        ace=ace.inicializarActividades();
        ace.setVisible(true);
    }//GEN-LAST:event_btnActEcoActionPerformed

    private void btnEmpleadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmpleadosActionPerformed
        EmpleadoView ev =null;
        ev= ev.inicializarEmpleado();
        ev.setVisible(true);
    }//GEN-LAST:event_btnEmpleadosActionPerformed

    private void btnGestionTercerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGestionTercerosActionPerformed
        PersonaTercerosView ptv = null;
        ptv=ptv.inicializarPersonaTerceros();
        ptv.setVisible(true);
        
    }//GEN-LAST:event_btnGestionTercerosActionPerformed

    private void btnRestore1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRestore1MouseClicked
        setExtendedState(this.NORMAL);
    }//GEN-LAST:event_btnRestore1MouseClicked

    private void btnClose1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnClose1MouseClicked
        dispose();
    }//GEN-LAST:event_btnClose1MouseClicked

    private void btnMaximize1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMaximize1MouseClicked

        setExtendedState(this.MAXIMIZED_BOTH);

        // TODO add your handling code here:
    }//GEN-LAST:event_btnMaximize1MouseClicked

    private void btnMinimized1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMinimized1MouseClicked
        setExtendedState(this.ICONIFIED);
    }//GEN-LAST:event_btnMinimized1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionInventarioHogarPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionInventarioHogarPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionInventarioHogarPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionInventarioHogarPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionInventarioHogarPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnActEco;
    private javax.swing.JMenuItem btnAdminInventario;
    private javax.swing.JMenuItem btnCatProd;
    private javax.swing.JLabel btnClose1;
    private javax.swing.JMenuItem btnEmpleados;
    private javax.swing.JMenuItem btnFacturacion;
    private javax.swing.JMenuItem btnGestionTerceros;
    private javax.swing.JLabel btnMaximize1;
    private javax.swing.JLabel btnMinimized1;
    private javax.swing.JMenuItem btnRegProductos;
    private javax.swing.JMenuItem btnRepresLegal;
    private javax.swing.JLabel btnRestore1;
    private javax.swing.JMenuItem btnSalir;
    private javax.swing.JMenuItem btnSucTerce;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
